PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#>  PREFIX dcterms: <http://purl.org/dc/terms/>  PREFIX skos: <http://www.w3.org/2004/02/skos/core#>   SELECT ?variable ?frequencySum ?numberOfCases ?country WHERE { { SELECT ?variable ?country ( SUM( ?frequency ) AS ?frequencySum ) WHERE { ?variable a disco:Variable ; disco:representation [ a skos:ConceptScheme ; skos:hasTopConcept ?code ] . ?statistics a disco:CategoryStatistics ; dcterms:spatial ?country ; disco:statisticsCategory ?code ; disco:frequency ?frequency . } GROUP BY ?variable ?country }  ?summary a disco:SummaryStatistics ; disco:statisticsVariable ?variable ; dcterms:spatial ?country ; disco:numberOfCases ?numberOfCases .  FILTER ( ?numberOfCases != ?frequencySum ) }