PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT ?variable ?frequencySum ?numberOfCasesSum WHERE { { SELECT ?conceptScheme ( SUM( ?frequency ) AS ?frequencySum ) WHERE { ?conceptScheme a skos:ConceptScheme ; skos:hasTopConcept ?code . ?statistics a disco:CategoryStatistics ; disco:statisticsCategory ?code ; disco:frequency ?frequency . } GROUP BY ?conceptScheme } { SELECT ?variable ( SUM( ?numberOfCases ) AS ?numberOfCasesSum ) WHERE { ?summary a disco:SummaryStatistics ; disco:statisticsVariable ?variable ; disco:numberOfCases ?numberOfCases . } GROUP BY ?variable } ?variable disco:representation ?conceptScheme . }