PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#> PREFIX missy: <http://lod.gesis.org/missy#> PREFIX gn: <http://www.geonames.org/ontology#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> SELECT ?studyGroupTitle ?studyTitle WHERE { ?study a disco:Study ; dcterms:title ?studyTitle ; dcterms:temporal [ a dcterms:PeriodOfTime ; disco:startDate ?startdate ] ; dcterms:publisher ?publisher ; disco:inGroup [ a disco:StudyGroup ; dcterms:title ?studyGroupTitle ] FILTER ( regex( ?publisher, "Eurostat", "i" ) ) FILTER ( ?startdate >= "2000-01-01T00:00:00"^^xsd:dateTime ) FILTER ( ?startdate < "2007-01-01T00:00:00"^^xsd:dateTime )} ORDER BY ?studyGroupTitle ?studyTitle
