PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT DISTINCT ?studyGroupTitle ?studyGroupAbstract WHERE { ?study a disco:Study ; disco:inGroup [ dcterms:title ?studyGroupTitle ; dcterms:abstract ?studyGroupAbstract ] ; disco:product [ a disco:LogicalDataSet ; disco:containsVariable [ a disco:Variable ; skos:notation ?variablenotation ]] . FILTER ( ?variablenotation = 'SEX' )} ORDER BY ?studyGroupTitle
