PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#> PREFIX missy: <http://lod.gesis.org/missy#> PREFIX gn: <http://www.geonames.org/ontology#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT ?question WHERE { ?study a disco:Study ; skos:prefLabel ?studyLabel ; disco:inGroup [ a disco:StudyGroup ; skos:prefLabel ?studyGroupLabel ] ; disco:instrument [ a disco:Questionnaire ; dcterms:description ?description ; missy:country [ gn:countryCode ?countryLabel ] ; disco:question ?question ] . ?question a disco:Question ; dcterms:identifier ?identifier ; disco:questionText ?questiontext . FILTER ( ?studyGroupLabel = 'EU-SILC'@en ) FILTER ( ?studyLabel = '2005'@en ) FILTER ( ?countryLabel = 'UK' ) FILTER ( ?description = 'basic questionnaire'@en ) FILTER ( ?identifier = 'd0225157-6f19-4ab1-8cab-130bee17c54c' )}
