PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT ( COUNT( DISTINCT ?variable ) as ?counter ) WHERE { ?logicalDataSet a disco:LogicalDataSet ; disco:containsVariable ?variable ; disco:isPublic "true"^^xsd:boolean . ?variable disco:concept [ skos:notation ?conceptNotation ] FILTER ( ?conceptNotation = 'Age' )}
