PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT DISTINCT ?vnotation WHERE { ?dataset a disco:LogicalDataSet ; dcterms:identifier ?identifier ; disco:containsVariable [ a disco:Variable ; skos:notation ?vnotation ] . FILTER ( ?identifier = '39625a58-4ad9-4acd-a1c0-ae7363444f37' )}
