PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#> PREFIX dcterms: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> SELECT DISTINCT ?notation ?label WHERE { ?variable a disco:Variable ; skos:notation ?variableNotation ; disco:representation [ a skos:ConceptScheme ; skos:hasTopConcept [ a skos:Concept ; skos:prefLabel ?label ; skos:notation ?notation ] ] Filter ( ?variableNotation = 'AGE' ) OPTIONAL { ?variable disco:question ?question }}
