PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  PREFIX disco: <http://rdf-vocabulary.ddialliance.org/discovery#>  PREFIX missy: <http://lod.gesis.org/missy#>  PREFIX dcterms: <http://purl.org/dc/terms/>  PREFIX gn: <http://www.geonames.org/ontology#>  PREFIX skos: <http://www.w3.org/2004/02/skos/core#>   SELECT DISTINCT ?countryLabel  WHERE {  ?statistics a disco:CategoryStatistics ;  disco:statisticsCategory ?topConcept ;  dcterms:spatial [ a dcterms:Location ;  dcterms:location ?countryLabel ]  { SELECT ?topConcept WHERE { ?study a disco:Study ;  skos:prefLabel ?studyLabel ;  disco:inGroup [   skos:prefLabel ?studyGroupLabel ] ;  disco:product [  skos:prefLabel ?datasetLabel ;  disco:containsVariable [ disco:representation [ skos:hasTopConcept ?topConcept ] ] ] .  FILTER ( ?studyGroupLabel = 'CIS'@en )  FILTER ( ?studyLabel = '2008'@en )  FILTER ( ?datasetLabel = 'cross-sec'@en ) } } }  ORDER BY ?countryLabel